# Generated by Django 4.0.4 on 2022-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cartproduct_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='completed',
            new_name='delivered',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='wear_size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL')], max_length=10),
        ),
        migrations.DeleteModel(
            name='SavedProduct',
        ),
    ]
