# Generated by Django 4.0.4 on 2022-07-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_alter_cartproduct_options_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_saved',
            new_name='is_sold_out',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Products',
                'ordering': ['-id'],
            },
        ),
    ]
