# Generated by Django 4.0.4 on 2022-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cartproduct_pro_exist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
