# Generated by Django 4.0.4 on 2022-09-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cartproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, choices=[('', ''), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wear_size',
            field=models.CharField(blank=True, choices=[('', ''), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL')], max_length=15, null=True),
        ),
    ]
