# Generated by Django 4.0.4 on 2022-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_len',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
