# Generated by Django 4.0.4 on 2022-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_sex_alter_product_photo_len'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-title', 'id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.CharField(blank=True, choices=[('Title', 'T'), ('Category', 'G'), ('Id', 'I'), ('Photo_len', 'P'), ('Sex', 'S')], default='id', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_len',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('mid-wide', 'MW')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('Unisex', 'U'), ('Male', 'M'), ('Female', 'F')], max_length=15, null=True),
        ),
    ]
