# Generated by Django 4.0.4 on 2022-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_options_product_sort_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('unisex', 'U'), ('male', 'M'), ('female', 'F')], max_length=15, null=True),
        ),
    ]
