# Generated by Django 4.0.4 on 2022-09-23 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold_out',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='ref',
            field=models.CharField(default=uuid.UUID('49151034-8118-46f2-a681-9d5f38c3b632'), max_length=20),
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
