# Generated by Django 4.0.4 on 2022-09-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_cartproduct_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproduct',
            name='saved',
            field=models.BooleanField(default=True),
        ),
    ]
