# Generated by Django 4.0.4 on 2022-09-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_savedproduct_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedproduct',
            options={'verbose_name_plural': 'Saved Products'},
        ),
        migrations.RemoveField(
            model_name='savedproduct',
            name='saved',
        ),
    ]
